services:
  - type: web
    name: my-backend-service
    repo: https://github.com/snowray23/budget-app
    branch: master
    root: Backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"