services:
  - type: web
    name: my-backend-service
    repo: https://github.com/snowray23/budget-app
    branch: main
    root: Backend
    buildCommand: <build-command>
    startCommand: <start-command>